### ISSUE TITLE
How to make this work on Linux?

### ISSUE THREAD

**Issue by SamLukeYes** [WEGFan/Geometry-Dash-Menu-Music-Randomizer#1]
Hi, there! I play Geometry Dash on Manjaro Linux, running it with Proton 5.0.9. When I tried to run this program in GD's prefix, I got the following output and the program stopped.
```
wineserver: using server-side synchronization.
0034:err:module:__wine_process_init L"C:\\windows\\system32\\winemenubuilder.exe" not found
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).
006c:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": 
c0000142
003c:fixme:service:scmdatabase_autostart_services Auto-start service L"wineusb" failed to start: 1114
GDMenuMusicRandomizer.exe.manifest could not be extracted!
fopen: Permission denied
0024:fixme:ver:GetCurrentPackageId (0x31fe94 (nil)): stub
```

**Comment by WEGFan** [comment]
我没用过 Proton 所以我也不是很清楚……我猜可能是 pyinstaller 的问题？我用 pyinstaller 4.0 重新打包了一下，你试试能不能打开

[GDMenuMusicRandomizer.zip](https://github.com/WEGFan/Geometry-Dash-Menu-Music-Randomizer/files/5128115/GDMenuMusicRandomizer.zip)

我这些内存地址是 Windows 下找的，我也不知道 Proton 里能不能用

**Comment by SamLukeYes** [comment]
> 我没用过 Proton 所以我也不是很清楚……我猜可能是 pyinstaller 的问题？我用 pyinstaller 4.0 重新打包了一下，你试试能不能打开
> 
> [GDMenuMusicRandomizer.zip](https://github.com/WEGFan/Geometry-Dash-Menu-Music-Randomizer/files/5128115/GDMenuMusicRandomizer.zip)
> 
> 我这些内存地址是 Windows 下找的，我也不知道 Proton 里能不能用

还是一模一样的错误

**Comment by WEGFan** [comment]
那没了……或许你可以试试从源码运行什么的
