### ISSUE TITLE
Freezes when changing songs

### ISSUE THREAD

**Issue by wentexp** [WEGFan/Geometry-Dash-Menu-Music-Randomizer#4]
I use a sorta low end laptop, so whenever it switches songs the game freezes for 1-3 seconds depending on how large the song is. This doesnt happen for my friend, who has a much better PC than mine, so this is definitely a result of the song randomizer using too much system resources.

**Comment by WEGFan** [comment]
The game needs to load the song from your hard drive if not loaded before, so it depends on how fast your hard drive is.
